const randomMessages = [
    "Have a great day! 🌞",
  "Keep up the good work! 👍",
  "You're doing amazing! 💪",
  "Don't forget to smile! 😊",
  "Stay positive and strong! 💪😊",
  "Believe in yourself! 🌟",
  "You are capable of great things! 🌟",
  "Every day is a new opportunity! 🌅",
  "You make a difference! 🌟",
  "Success is just around the corner! 🌟",
  "Take it one step at a time! 🚶‍♂️",
  "You are appreciated! 🌟",
  "Chase your dreams! 🌟✨",
  "Keep pushing forward! 🚀",
  "Your efforts matter! 🌟",
  "Stay focused and determined! 🔍💪",
  "Embrace the journey! 🌟",
  "You have the power to succeed! 💪🌟",
  "Make today count! 📅",
  "You are unstoppable! 🌟💪",
  "Never give up! 🚫😊",
  "You are a star! 🌟",
  "Keep shining bright! ✨",
  "Stay humble and kind! 🙏",
  "You are an inspiration! 🌟",
  "You have a beautiful soul! ✨",
  "Keep moving forward! ➡️🌟",
  "You are loved! ❤️",
  "Dream big! 🌟",
  "Your potential is limitless! 🌟",
  "You are unique! 🌟",
  "Keep learning and growing! 📚🌱",
  "You are a warrior! ⚔️🌟",
  "Stay true to yourself! 💯",
  "Your hard work pays off! 💪💰",
  "You have a heart of gold! 💛",
  "Keep your head up! 🌟",
  "You are amazing just the way you are! ✨",
  "Believe in the magic of possibilities! ✨",
  "You are stronger than you think! 💪",
  "You are a ray of sunshine! 🌞",
  "Keep spreading positivity! 🌟",
  "You are a treasure! 💎",
  "You are brave and courageous! 💪🌟",
  "You are a blessing! 🌟",
  "Your smile lights up the room! 😊",
  "You are full of potential! 🌟",
  "Keep dreaming and achieving! 🌟✨",
  "You are a masterpiece! 🎨",
  "Stay passionate and driven! 🔥🌟"
];

export const getRandomMessage = () => {
    return randomMessages[Math.floor(Math.random() * randomMessages.length)];
}

